[tool.poetry]
name = "analyzer"
version = "0.1.0"
description = ""
authors = ["Corentin DuchÃªne <corentin.duchene@epita.fr>"]

[tool.poetry.dependencies]
python = "3.8.10"
pyspark = "^3.2.1"
matplotlib = "^3.5.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
